BEGIN;
DO $$ DECLARE admin_id uuid;u uuid:=gen_random_uuid();sid uuid:=gen_random_uuid();r jsonb;
BEGIN
 SELECT a.id INTO admin_id FROM auth.users a JOIN talkroom_private.admin_emails b ON lower(a.email)=b.email WHERE a.email_confirmed_at IS NOT NULL LIMIT 1;
 ASSERT admin_id IS NOT NULL;
 INSERT INTO talkroom_private.sessions(id,user_id,room,username,peer_id,role) VALUES(sid,u,'VOICE_TEST','QA pool','qa-'||sid,'member');
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
 BEGIN PERFORM public.talkroom_turn_manage('list');RAISE EXCEPTION 'non-admin allowed';EXCEPTION WHEN insufficient_privilege THEN NULL;END;
 BEGIN PERFORM public.talkroom_device_logs('{}');RAISE EXCEPTION 'non-admin logs allowed';EXCEPTION WHEN insufficient_privilege THEN NULL;END;
 PERFORM public.talkroom_device_context(sid,'{"client_type":"web","app_version":"qa"}');
 ASSERT (SELECT client->>'app_version'='qa' FROM talkroom_private.device_audit WHERE session_id=sid);
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',admin_id,'role','authenticated')::text,true);
 PERFORM public.talkroom_turn_manage('save',jsonb_build_object('slot','G','provider','static','label','QA','quota_mb',100,'usage_mb',0,'ice_servers',jsonb_build_array(jsonb_build_object('urls','turn:example.com:443','username','qa','credential','qa'))));
 PERFORM public.talkroom_turn_manage('route','{"room":"VOICE_TEST","slot":"A","fallback":["G"]}');
 r:=public.talkroom_turn_manage('list');ASSERT NOT (r->'servers'->0 ? 'secret');ASSERT NOT (r->'servers'->0 ? 'ice_servers');
 UPDATE talkroom_private.turn_servers SET usage_mb=500,quota_mb=500,provider_quota_mb=500 WHERE slot='A';
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
 r:=public.talkroom_turn_resolve(sid);ASSERT r->>'slot'='G','did not fail over';
 ASSERT (SELECT active_slot='G' FROM talkroom_private.turn_routes WHERE room='VOICE_TEST');
 UPDATE talkroom_private.turn_servers SET usage_mb=100 WHERE slot='G';
 BEGIN PERFORM public.talkroom_turn_resolve(sid);RAISE EXCEPTION 'exhausted allowed';EXCEPTION WHEN raise_exception THEN IF SQLERRM='exhausted allowed' THEN RAISE;END IF;END;
 UPDATE talkroom_private.sessions SET expires_at=now() WHERE id=sid;
 BEGIN PERFORM public.talkroom_turn_resolve(sid);RAISE EXCEPTION 'expired allowed';EXCEPTION WHEN insufficient_privilege THEN NULL;END;
 ASSERT NOT has_function_privilege('authenticated','public.talkroom_turn_usage_claim()','EXECUTE');
 ASSERT NOT has_table_privilege('authenticated','talkroom_private.turn_servers','SELECT');
 DELETE FROM talkroom_private.sessions WHERE id=sid;
 ASSERT (SELECT ended_at IS NOT NULL FROM talkroom_private.device_audit WHERE session_id=sid);
END;$$;
ROLLBACK;
